apiVersion: config.mas.ibm.com/v1
kind: KafkaCfg
metadata:
  name: {{ .Values.masapp.instanceid }}-kafka-system
  namespace: {{ .Values.masapp.core-namespace | quote }}
  labels:
    mas.ibm.com/configScope: system
    mas.ibm.com/instanceId: {{ .Values.masapp.instanceid | quote }}
    {{- include "ibm-masapp-kafka.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3" 
spec:
  displayName: {{ .Values.kafka.displayname | quote }}
  config:
    hosts:
      - host: {{ .Values.boothost | quote }}
        port: 443
    credentials:
      secretName: maskafka-credentials
    saslMechanism: SCRAM-SHA-512
  certificates:
    - alias: {{ .Values.kafka.name }}-ca
      crt: |-
{{ .Values.bootcert | nindent 8  }}        
